//! Detectors: attach an OWNER and a CONSEQUENCE to a candidate root.
//!
//! Hard rules from the spec, enforced here:
//!   - a directory NAME never authorizes anything; corroborating project
//!     metadata must be present
//!   - manifests are parsed as inert data, never executed
//!   - "not referenced by the metadata we checked" is never "unused"
//!   - evidence is qualitative (corroborated / partial / weak), never an
//!     invented confidence percentage
//!   - mtime is not last-use time and is never used to infer disposability

use std::collections::HashSet;
use std::path::{Path, PathBuf};

use crate::scan::{Entry, ScanResult};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Evidence {
    /// Multiple independent facts agree (manifest + expected layout).
    Corroborated,
    /// The shape matches but a corroborating fact is missing.
    Partial,
    /// Recognized by name/extension only — explicitly NOT actionable.
    Weak,
}

impl Evidence {
    pub fn as_str(&self) -> &'static str {
        match self {
            Evidence::Corroborated => "corroborated",
            Evidence::Partial => "partial",
            Evidence::Weak => "weak",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Consequence {
    /// Regenerated by a build, given the toolchain and dependencies.
    ConditionalRebuild,
    /// Restored by re-running a package manager: needs network, maybe auth,
    /// and may run lifecycle scripts.
    RequiresDownload,
    /// May be unique. Never eligible for automatic action.
    PotentiallyUnique,
    Unknown,
}

impl Consequence {
    pub fn as_str(&self) -> &'static str {
        match self {
            Consequence::ConditionalRebuild => "conditional_rebuild",
            Consequence::RequiresDownload => "requires_download",
            Consequence::PotentiallyUnique => "potentially_unique",
            Consequence::Unknown => "unknown",
        }
    }
    pub fn summary(&self) -> &'static str {
        match self {
            Consequence::ConditionalRebuild =>
                "Next build regenerates these outputs. Requires the toolchain and dependencies; \
                 artifacts from an unavailable build environment may not be reproducible.",
            Consequence::RequiresDownload =>
                "Reinstalling requires network access, possibly registry authentication, and may \
                 re-run install scripts. A lockfile does not guarantee the upstream packages still exist.",
            Consequence::PotentiallyUnique =>
                "Recovery source is unverified. This may be the only copy.",
            Consequence::Unknown =>
                "No owner identified. Consequence of removal is unknown.",
        }
    }
}

#[derive(Debug, Clone)]
pub struct Finding {
    pub path: PathBuf,
    pub category: String,
    pub owner_kind: String,
    pub owner_root: Option<PathBuf>,
    pub evidence: Evidence,
    /// Human-readable facts that produced the classification.
    pub evidence_facts: Vec<String>,
    pub consequence: Consequence,
    /// Allocated bytes in this subtree, each inode counted once.
    pub allocated: u64,
    pub logical: u64,
    pub file_count: usize,
    /// True when some inode in this subtree also has links OUTSIDE it — the
    /// blocks cannot be reclaimed by removing this subtree alone.
    pub external_links: bool,
    /// Why a reclaimable estimate is unavailable, when it is.
    pub reclaimable_unknown_reason: Option<String>,
    pub cleanup_eligible: bool,
    pub cleanup_blocked_reason: Option<String>,
    pub rule_version: &'static str,
}

const RULE_VERSION: &str = "detect/0.1.0";

pub fn detect(scan: &ScanResult) -> Vec<Finding> {
    let mut candidates: Vec<Finding> = Vec::new();

    for e in scan.entries.iter().filter(|e| e.is_dir && !e.is_symlink) {
        let name = match e.path.file_name().and_then(|n| n.to_str()) {
            Some(n) => n,
            None => continue,
        };
        let parent = e.path.parent().map(|p| p.to_path_buf());

        let found = match name {
            "target" => detect_cargo_target(&e.path, parent.as_deref()),
            "node_modules" => detect_node_modules(&e.path, parent.as_deref()),
            "__pycache__" => detect_pycache(&e.path, parent.as_deref()),
            _ => {
                if e.path.join("pyvenv.cfg").is_file() {
                    detect_venv(&e.path)
                } else {
                    None
                }
            }
        };
        if let Some(f) = found {
            candidates.push(f);
        }
    }

    // Model files are findings in their own right: large, and never
    // automatically removable because origin cannot be assumed.
    for e in scan.entries.iter().filter(|e| !e.is_dir && !e.is_symlink) {
        if let Some(ext) = e.path.extension().and_then(|x| x.to_str()) {
            if ext.eq_ignore_ascii_case("gguf") || ext.eq_ignore_ascii_case("safetensors") {
                candidates.push(Finding {
                    path: e.path.clone(),
                    category: format!("model.{}", ext.to_lowercase()),
                    owner_kind: "unknown".into(),
                    owner_root: None,
                    evidence: Evidence::Weak,
                    evidence_facts: vec![format!(
                        "file extension .{} only; header not parsed in v0.1, origin unverified",
                        ext.to_lowercase()
                    )],
                    consequence: Consequence::PotentiallyUnique,
                    allocated: e.allocated,
                    logical: e.logical,
                    file_count: 1,
                    external_links: e.nlink > 1,
                    reclaimable_unknown_reason: None,
                    cleanup_eligible: false,
                    cleanup_blocked_reason: Some(
                        "model origin unverified; manual review only in v0.1".into(),
                    ),
                    rule_version: RULE_VERSION,
                });
            }
        }
    }

    // Drop findings nested inside another finding: a node_modules inside a
    // node_modules is drill-down evidence, not a second candidate. Without this
    // the same blocks are presented twice and the totals lie.
    candidates.sort_by(|a, b| a.path.as_os_str().len().cmp(&b.path.as_os_str().len()));
    let mut roots: Vec<Finding> = Vec::new();
    for c in candidates {
        let nested = roots.iter().any(|r| c.path.starts_with(&r.path) && c.path != r.path);
        if !nested {
            roots.push(c);
        }
    }

    // Size each surviving root from the scan, deduping inodes within it.
    for f in roots.iter_mut() {
        size_finding(f, scan);
    }
    roots.sort_by(|a, b| b.allocated.cmp(&a.allocated));
    roots
}

fn size_finding(f: &mut Finding, scan: &ScanResult) {
    let mut seen: HashSet<(u64, u64)> = HashSet::new();
    let mut allocated = 0u64;
    let mut logical = 0u64;
    let mut files = 0usize;
    let mut external_links = false;

    // Inodes inside this subtree, so we can tell whether a multi-link file has
    // its other links inside or outside.
    let inside: HashSet<(u64, u64)> = scan
        .entries
        .iter()
        .filter(|e| !e.is_dir && !e.is_symlink && e.path.starts_with(&f.path))
        .map(|e| (e.dev, e.ino))
        .collect();

    let mut link_counts: std::collections::HashMap<(u64, u64), u64> =
        std::collections::HashMap::new();
    for e in scan
        .entries
        .iter()
        .filter(|e| !e.is_dir && !e.is_symlink && e.path.starts_with(&f.path))
    {
        *link_counts.entry((e.dev, e.ino)).or_insert(0) += 1;
    }

    for e in scan
        .entries
        .iter()
        .filter(|e: &&Entry| !e.is_dir && !e.is_symlink && e.path.starts_with(&f.path))
    {
        let key = (e.dev, e.ino);
        if seen.insert(key) {
            allocated += e.allocated;
            logical += e.logical;
        }
        files += 1;
        // nlink counts ALL links on the filesystem; if more exist than we found
        // inside this subtree, at least one lives outside it.
        if e.nlink > 1 {
            let inside_count = *link_counts.get(&key).unwrap_or(&0);
            if e.nlink > inside_count && inside.contains(&key) {
                external_links = true;
            }
        }
    }

    f.allocated = allocated;
    f.logical = logical;
    f.file_count = files;
    f.external_links = external_links;
    if external_links {
        f.reclaimable_unknown_reason = Some(
            "one or more inodes in this subtree have hard links outside it; removing this path \
             alone does not free their blocks"
                .into(),
        );
    }
    if !scan.complete {
        f.reclaimable_unknown_reason.get_or_insert(
            "scan coverage was incomplete, so this subtree's total is a lower bound".into(),
        );
    }
}

fn detect_cargo_target(path: &Path, parent: Option<&Path>) -> Option<Finding> {
    let parent = parent?;
    let manifest = parent.join("Cargo.toml");
    let mut facts = Vec::new();
    let mut evidence = Evidence::Partial;

    if !manifest.is_file() {
        // A directory called "target" with no Cargo.toml beside it is NOT a
        // build directory as far as we are concerned.
        return Some(unknown_dir(path, "directory named 'target' with no Cargo.toml in the parent"));
    }
    facts.push(format!("cargo manifest present at {}", manifest.display()));

    // Expected build layout is the corroborating fact.
    let layout_hits: Vec<&str> = ["debug", "release", "CACHEDIR.TAG", ".rustc_info.json"]
        .into_iter()
        .filter(|n| path.join(n).exists())
        .collect();
    if !layout_hits.is_empty() {
        facts.push(format!("cargo build layout present: {}", layout_hits.join(", ")));
        evidence = Evidence::Corroborated;
    }

    // Tracked source inside a build directory is a stop sign.
    let tracked = path.join(".git").exists();
    let (eligible, blocked) = if tracked {
        (false, Some("contains a .git directory — not treated as build output".to_string()))
    } else if evidence != Evidence::Corroborated {
        (false, Some("build layout not corroborated".to_string()))
    } else {
        // v0.1 is READ-ONLY. Eligibility is computed but never acted on.
        (false, Some("v0.1 is read-only; no cleanup is performed".to_string()))
    };

    Some(Finding {
        path: path.to_path_buf(),
        category: "rust.build_output".into(),
        owner_kind: "cargo_project".into(),
        owner_root: Some(parent.to_path_buf()),
        evidence,
        evidence_facts: facts,
        consequence: Consequence::ConditionalRebuild,
        allocated: 0,
        logical: 0,
        file_count: 0,
        external_links: false,
        reclaimable_unknown_reason: None,
        cleanup_eligible: eligible,
        cleanup_blocked_reason: blocked,
        rule_version: RULE_VERSION,
    })
}

fn detect_node_modules(path: &Path, parent: Option<&Path>) -> Option<Finding> {
    let parent = parent?;
    let pkg = parent.join("package.json");
    if !pkg.is_file() {
        return Some(unknown_dir(
            path,
            "directory named 'node_modules' with no package.json in the parent",
        ));
    }
    let mut facts = vec![format!("package manifest present at {}", pkg.display())];
    let locks: Vec<&str> = ["package-lock.json", "pnpm-lock.yaml", "yarn.lock", "bun.lockb"]
        .into_iter()
        .filter(|n| parent.join(n).is_file())
        .collect();
    let evidence = if locks.is_empty() {
        facts.push("no lockfile found — restoration may not be reproducible".into());
        Evidence::Partial
    } else {
        facts.push(format!("lockfile present: {}", locks.join(", ")));
        Evidence::Corroborated
    };

    Some(Finding {
        path: path.to_path_buf(),
        category: "node.dependencies".into(),
        owner_kind: "node_project".into(),
        owner_root: Some(parent.to_path_buf()),
        evidence,
        evidence_facts: facts,
        consequence: Consequence::RequiresDownload,
        allocated: 0,
        logical: 0,
        file_count: 0,
        external_links: false,
        reclaimable_unknown_reason: None,
        cleanup_eligible: false,
        cleanup_blocked_reason: Some("v0.1 is read-only; no cleanup is performed".into()),
        rule_version: RULE_VERSION,
    })
}

fn detect_pycache(path: &Path, parent: Option<&Path>) -> Option<Finding> {
    let parent = parent?;
    let has_py = std::fs::read_dir(parent)
        .ok()
        .map(|rd| {
            rd.flatten()
                .any(|e| e.path().extension().and_then(|x| x.to_str()) == Some("py"))
        })
        .unwrap_or(false);
    let (evidence, facts) = if has_py {
        (
            Evidence::Corroborated,
            vec![format!("matching .py sources present in {}", parent.display())],
        )
    } else {
        (
            Evidence::Partial,
            vec!["no matching .py sources beside the cache — may be a bytecode-only distribution".into()],
        )
    };
    Some(Finding {
        path: path.to_path_buf(),
        category: "python.bytecode".into(),
        owner_kind: "python_package".into(),
        owner_root: Some(parent.to_path_buf()),
        evidence,
        evidence_facts: facts,
        consequence: Consequence::ConditionalRebuild,
        allocated: 0,
        logical: 0,
        file_count: 0,
        external_links: false,
        reclaimable_unknown_reason: None,
        cleanup_eligible: false,
        cleanup_blocked_reason: Some("v0.1 is read-only; no cleanup is performed".into()),
        rule_version: RULE_VERSION,
    })
}

fn detect_venv(path: &Path) -> Option<Finding> {
    let cfg = path.join("pyvenv.cfg");
    let mut facts = vec![format!("virtual environment marker at {}", cfg.display())];
    // Restoration is only knowable if the project declares its requirements.
    let reqs: Vec<&str> = ["requirements.txt", "pyproject.toml", "Pipfile", "poetry.lock"]
        .into_iter()
        .filter(|n| path.parent().map(|p| p.join(n).is_file()).unwrap_or(false))
        .collect();
    let (evidence, consequence) = if reqs.is_empty() {
        facts.push(
            "no dependency manifest beside the environment — recreating it requires knowing the \
             requirements, which we cannot read from here"
                .into(),
        );
        (Evidence::Partial, Consequence::PotentiallyUnique)
    } else {
        facts.push(format!("dependency manifest present: {}", reqs.join(", ")));
        (Evidence::Corroborated, Consequence::RequiresDownload)
    };
    Some(Finding {
        path: path.to_path_buf(),
        category: "python.virtualenv".into(),
        owner_kind: "python_venv".into(),
        owner_root: path.parent().map(|p| p.to_path_buf()),
        evidence,
        evidence_facts: facts,
        consequence,
        allocated: 0,
        logical: 0,
        file_count: 0,
        external_links: false,
        reclaimable_unknown_reason: None,
        cleanup_eligible: false,
        cleanup_blocked_reason: Some("v0.1 is read-only; no cleanup is performed".into()),
        rule_version: RULE_VERSION,
    })
}

/// A misleading directory name stays UNKNOWN. This is the fixture the spec
/// calls out: `target` holding tracked source must never look disposable.
fn unknown_dir(path: &Path, why: &str) -> Finding {
    Finding {
        path: path.to_path_buf(),
        category: "unknown".into(),
        owner_kind: "unknown".into(),
        owner_root: None,
        evidence: Evidence::Weak,
        evidence_facts: vec![why.to_string()],
        consequence: Consequence::Unknown,
        allocated: 0,
        logical: 0,
        file_count: 0,
        external_links: false,
        reclaimable_unknown_reason: None,
        cleanup_eligible: false,
        cleanup_blocked_reason: Some("no owner identified".into()),
        rule_version: RULE_VERSION,
    }
}
